name: Build and Release Alfred Workflow

on:
  push:
    branches: [ master, main, develop ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Get version from info.plist
      id: version
      run: |
        VERSION=$(plutil -extract version raw info.plist)
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Workflow version: $VERSION"
        
    - name: Build workflow
      run: |
        chmod +x build.sh
        ./build.sh
        
    - name: Verify build
      run: |
        test -f ClickUp.alfredworkflow || exit 1
        unzip -t ClickUp.alfredworkflow
        echo "✅ Workflow built successfully"
        
    - name: Upload workflow artifact
      uses: actions/upload-artifact@v3
      with:
        name: ClickUp-v${{ steps.version.outputs.VERSION }}.alfredworkflow
        path: ClickUp.alfredworkflow
        retention-days: 30
        
  release:
    needs: build
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Get version info
      id: version
      run: |
        # Get version from tag
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_OUTPUT
        
        # Get version from info.plist
        PLIST_VERSION=$(plutil -extract version raw info.plist)
        echo "PLIST_VERSION=$PLIST_VERSION" >> $GITHUB_OUTPUT
        
        # Verify versions match
        if [ "$TAG_VERSION" != "$PLIST_VERSION" ]; then
          echo "❌ Version mismatch!"
          echo "Tag version: $TAG_VERSION"
          echo "info.plist version: $PLIST_VERSION"
          echo "Please ensure the tag version matches the version in info.plist"
          exit 1
        fi
        
        echo "✅ Version check passed: $TAG_VERSION"
        
    - name: Build workflow
      run: |
        chmod +x build.sh
        ./build.sh
        
    - name: Generate changelog
      id: changelog
      run: |
        # Get commits since last tag
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        if [ -z "$PREVIOUS_TAG" ]; then
          echo "No previous tag found, including all commits"
          COMMITS=$(git log --pretty=format:"- %s" | head -20)
        else
          echo "Generating changelog since $PREVIOUS_TAG"
          COMMITS=$(git log --pretty=format:"- %s" $PREVIOUS_TAG..HEAD)
        fi
        
        # Create changelog
        cat > CHANGELOG.md << EOF
        ## What's Changed in v${{ steps.version.outputs.TAG_VERSION }}
        
        $COMMITS
        
        ## Installation
        
        1. Download the \`ClickUp.alfredworkflow\` file below
        2. Double-click to install in Alfred
        3. Configure your API key with \`cu:config\`
        
        ## Requirements
        
        - Alfred 5+ with Powerpack
        - macOS 10.15+ (Python 3.9+ included)
        - ClickUp API key from https://app.clickup.com/settings/apps
        EOF
        
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        cat CHANGELOG.md >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: ClickUp Alfred Workflow v${{ steps.version.outputs.TAG_VERSION }}
        body: ${{ steps.changelog.outputs.changelog }}
        files: ClickUp.alfredworkflow
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}